export const ADD_ITEMS = "ADD_ITEMS";
export const RESET_ITEMS = "RESET_ITEMS";

export const SET_HEADERVISIBILITY = "SET_HEADERVISIBILITY";
export const SET_HEADERBTN = "SET_HEADERBTN";
export const SET_HEADERBOTH = "SET_HEADERBTN";
export const SET_HEADERMENUBTN = "SET_HEADERMENUBTN";
export const RESET_HEADERMENUBTN = "RESET_HEADERMENUBTN";

export const SET_SHOW_DRAWER = "SET_SHOW_DRAWER";
